version: "3"
services:
  server:
    build:
      context: .
    command: node server.js
    ports: [8080]  
  wss:
    build:
      context: .
    command: node wss.js
    ports: [8080]  
  nginx:
    image: nginx
    volumes: 
      - ./sse.conf:/etc/nginx/conf.d/sse.conf
      - ./wss.conf:/etc/nginx/conf.d/wss.conf
      - ./ssl/:/etc/nginx/ssl/
    ports:
      - 8443:8443
      - 8444:8444
    depends_on:
      - server
      - wss
